version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:alpine
    ports:
        - "8989:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - app-php

networks:
  app-php:
    driver: bridge